# Generated by Django 2.1.2 on 2021-06-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_chat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='mesages',
        ),
    ]
